### ISSUE TITLE
Issue with iPhone Simulator

### ISSUE THREAD

**Issue by Aravinda766** [damienaicheh/MicrosoftAuthenticationProject#2]
I followed the instructions in the post. But I was stuck with missing provisioning profile error. Finally, I had to setup "App Store"provisioning profile to get it woking. Following link was helpful:
https://hyperpad.zendesk.com/hc/en-us/articles/204378199-Create-a-Distribution-Provisioning-Profile

Hopefully this will help someone.
Hopefully this will help someone.
Could you please update your post with provisioning profile information?

**Comment by sachinskamat** [comment]
I followed the instructions in the post, but have run into an issue with providing the return URI while working on android application. I think it is related to registering the application on Microsoft Azure, Could you please clarify what has been missed out?
![Screenshot_20200211-174058](https://user-images.githubusercontent.com/42957266/74235997-3d293d00-4cf6-11ea-9613-428baaa32285.jpg)

**Comment by Aravinda766** [comment]
Hi, There are few things: 1. Please follow the instructions in below post. Create a Distribution Provisioning Profile
2. Please login to your App Store Developer account and setup provisioning profile. You will have to use this provisioning profile in project settings.3. Also, if you are using latest MSAL library(Microsoft.Identity.Client) , following works.

Hopefully this fixes the issue.

Thanks,Aravinda


   
    On Tuesday, February 11, 2020, 05:47:20 PM GMT+5:30, sachinskamat <notifications@github.com> wrote:  
 
 
I followed the instructions in the post, but have run into an issue with providing the return URI while working on android application. I think it is related to registering the application on Microsoft Azure, Could you please clarify what has been missed out?
